### ISSUE TITLE
Link to documentation recurses

### ISSUE THREAD

**Issue by wimjongman** [equoplatform/monaco-editor#4]
You have a link in the readme
[
https://docs.equoplatform.com/framework/1.1.x/components/equo-editor.html#_how_to_use_equo_editor](
https://docs.equoplatform.com/framework/1.1.x/components/equo-editor.html#_how_to_use_equo_editor)

That runs in a loop

**Comment by maquinas07** [comment]
Sorry, that link is outdated, it should be: https://docs.equo.dev/sdk/1.0.x/components/equo-editor.html#_how_to_use_equo_editor. We'll update it in the README shortly.
